name: admin
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.1 <3.0.0'

dependencies: 
  form_validator: 1.0.2
  flutter_bloc: 8.1.1
  image_picker: 0.8.6
  intl: 0.17.0
  equatable: 2.0.5
  formz: 0.4.1
  dio: 4.0.6
  cupertino_icons: ^1.0.2
  flutter_easyloading: 3.0.5
  dropdown_textfield: 1.0.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

