name: shoea
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  google_fonts: 3.0.1
  line_icons: 2.0.1
  ionicons: 0.2.1
  introduction_screen: 3.0.2
  responsive_sizer: 3.1.1
  loading_animation_widget: 1.2.0+3
  form_validator: 1.0.2
  flutter_bloc: 8.1.1
  image_picker: 0.8.6
  intl: 0.17.0
  equatable: 2.0.5
  formz: 0.4.1
  dropdown_textfield: 1.0.5
  fluid_bottom_nav_bar: 1.3.0
  carousel_slider: 4.1.1
  simple_icons: 7.10.0
  flutter_credit_card: 3.0.4
  modal_bottom_sheet: 2.1.2
  sticky_headers: 0.3.0+2
  lottie: 1.4.3
  readmore: 2.2.0
  timeago: 3.3.0
  pin_code_fields: 7.4.0
  awesome_dialog: 3.0.2
  flutter_rating_bar: 4.0.1
  barcode_widget: 2.0.3
  random_string: 2.3.1
  google_maps_flutter: ^2.2.1
  flutter_sticky_header: ^0.6.4
  dio: 4.0.6
  get_storage: 2.0.3
  jwt_decoder: 2.0.1
  flutter_easyloading: 3.0.5
  skeleton_text: 3.0.0
  geolocator: 9.0.2
  dropdown_search: ^5.0.3
  darq: ^1.2.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - asset/user/
    - asset/onboarding/
    - asset/carousel/
    - asset/shoes/
    - asset/lottie/
  uses-material-design: true

